name: Convert players.yaml to json

on: push

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -e .

      - name: Run Conversion
        run: python -m ard_utility convert

      - name: Update main branch
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              git config --local user.email "action@github.com";
              git config --local user.name "ConvertToJson";
              git commit -am "chore: Convert players.yaml to json";
              git push origin HEAD:master;
          else
            echo "no changes";
          fi
